### ISSUE TITLE
Bug - Payment Error Handling

### ISSUE THREAD

**Issue by CurseReverse** [Soneso/stellar-php-sdk#27]
Trying to send a custom asset payment.  If the payment fails (for example, from insufficient funds, or an inactive destination address) the script breaks and I'm unable to see the error code from Stellar, or do anything else.  If the payment would have been successful, no issue.

I'm trying to submit the transaction like this:
`$response = $sdk->submitTransaction($transaction);`

It also breaks if I submit it like this (from an example in the examples folder):
```
try {
    $response = $sdk->submitTransaction($transaction);
} catch (HorizonRequestException $e) {
    print("Error submitting payment");
}
```

Can someone take a look, thank you.

**Error logs:**
[04-Aug-2023 02:51:45 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST **https://horizon.stellar.org/transactions?tx=AAAAAgAAAABNLuPlAK7znCjewDo%2Fcesy8k2WfT3Wzv3uEQT5sWkHcwAAAGQCCwxwAAAAGwAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAFl2UuwGhasIYsC3iEzdTylUiJxhTCg%2B2aB%2F%2FIkW8ScpAAAAAldhbHJ1c0NvaW4AAAAAAABgIf%2FzshITxLLr2hDJwtIoIQZyqN5D8brtivzcglD4fgAAAAAAAbGYAAAAAAAAAAGxaQdzAAAAQMrAldm9lhr5jNVvGXDBlu7YssiQfACcBZyA7%2F2HpvAcnAZKr84yYochZainlenDXQFrGiAsXyWTFpi1QBSbIgE%3D**` resulted in a `400 Bad Request` response:
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  (truncated...)
 in stellar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 stellar/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 stellar/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 stellar/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 stellar/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 stellar/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 stellar/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 stellar/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 stellar/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 stellar/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 stellar/vendor/guzzlehttp/guzzle/src/Client.php(124): GuzzleHttp\Promise\Promise->wait()
#10 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Requests/RequestBuilder.php(101): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request))
#11 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Requests/SubmitTransactionRequestBuilder.php(33): Soneso\StellarSDK\Requests\RequestBuilder->executeRequest('/transactions?t...', 'submit_transact...', 'POST')
#12 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Requests/SubmitTransactionRequestBuilder.php(41): Soneso\StellarSDK\Requests\SubmitTransactionRequestBuilder->request('/transactions?t...')
#13 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/StellarSDK.php(277): Soneso\StellarSDK\Requests\SubmitTransactionRequestBuilder->execute()
#14 stellar/sendpayment.php(38): Soneso\StellarSDK\StellarSDK->submitTransaction(Object(Soneso\StellarSDK\Transaction))
#15 {main}

Next Soneso\StellarSDK\Exceptions\HorizonRequestException: The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-failed/ in stellar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Requests/RequestBuilder.php(104): Soneso\StellarSDK\Exceptions\HorizonRequestException::fromOtherException('/transactions?t...', 'POST', Object(GuzzleHttp\Exception\ClientException), NULL)
#1 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Requests/SubmitTransactionRequestBuilder.php(33): Soneso\StellarSDK\Requests\RequestBuilder->executeRequest('/transactions?t...', 'submit_transact...', 'POST')
#2 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Requests/SubmitTransactionRequestBuilder.php(41): Soneso\StellarSDK\Requests\SubmitTransactionRequestBuilder->request('/transactions?t...')
#3 stellar/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/StellarSDK.php(277): Soneso\StellarSDK\Requests\SubmitTransactionRequestBuilder->execute()

**Comment by CurseReverse** [comment]
Closing, this is my bad.

Needed to change `HorizonRequestException $e` to `Exceptions\HorizonRequestException $e`

Still struggling to get the Stellar generated error messages such as `INSUFFICIENT_BALANCE` etc
